name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        # List of keymap files to build
        keyboards:
          - lily58
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build firmware
        run: make ${{ matrix.keyboards }}

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: ${{ matrix.keyboards }}_${{ github.actor }}
          path: |
            *.uf2
          